name: gbdt-binning
channels:
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn=1.4
  - lightgbm=4.3
  - xgboost=2.0
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
      - openml
